# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301d20df341887e28fbafcf081713a3d2990fab24dc001f8225e02a2a74b7da83ed89b266c1463e1254d5cfafce1358243fdaf01f5558b88aae39149576a08cb

test:
  secret_key_base: 3ed722144de843ac6967ba899514fde2db541bcdec239d4cfbfc3a5383e8713d24946ce206bdd889c3da6f314b9437298c1b3c39fb2b575a97f9bf424ada5de8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
